# config/cucumber.yml
##YAML Template

<% test_batch_id = "#{ENV['TEST_ENV_NUMBER']}" %>
<% plataforma = "#{ENV['PARALLEL']}" %>

default: --no-source --color --format pretty -p json -p progress
rerun: RERUN=rerun

parallel: PLATFORM=<%= plataforma %><%= test_batch_id %> -p default -p retry parallel_cucumber features/ SCREENSHOT_PATH=/report/log -r features/support -r features/page_objects -r features/support/page_helper -r features/step_definitions -r features/gherkins 'not @wip'
pretty:   --format pretty
progress: --format progress
usage:    --format usage
retry:    --retry 1
json:     --format json --out report/report.json

# Reports
html_report: --format pretty  --format html --out report/report_<%= Time.now.strftime("%d%m%Y_%H%M%S") %>.html
json_report: --format pretty  --format html --out report/report_<%= Time.now.strftime("%d%m%Y_%H%M%S") %>.json
rerun_html_report: --format pretty --format html --out report/report_rerun_<%= Time.now.strftime("%d%m%Y_%H%M%S") %>.html
rerun_json_report: --format pretty --format html --out report/report_rerun_<%= Time.now.strftime("%d%m%Y_%H%M%S") %>.json
console_output_color: --color

# Simulador iOS LOCAL
iphone_8: PLATFORM=ios
iphone_8_plus: PLATFORM=ios2
iphone_11: PLATFORM=ios3
iphone_11_pro: PLATFORM=ios4
iphone_11_pro_max: PLATFORM=ios5

# Emulador Android LOCAL
nexus_5x: PLATFORM=android

# Device Real Android LOCAL
samsung: PLATFORM=android2

# Sauce Emulador e Simulador
iphone_xr_simulator: PLATFORM=simulador_sauce_ios
iphone_8_simulador: PLATFORM=simulador_sauce_ios2
iphone_7_simulator: PLATFORM=simulador_sauce_ios2

samsung_galaxy_s9: PLATFORM=emulador_sauce_android
samsung_galaxy_s7: PLATFORM=emulador_sauce_android2
samsung_galaxy_s8: PLATFORM=emulador_sauce_android3

# plataforma
ios: SO=ios -p default
android: SO=android -p default
emulador_sauce_android: SO=emulador_sauce_android -p default
simulador_sauce_ios: SO=simulador_sauce_ios -p default


