pipeline {
   agent {
     docker {
       image 'qaninja/rubywd'
     }
   }

   stages {
      stage('Build') {
         steps {
            echo 'Remove lock e install bundler'
         }
        }
        stage('Test') {
         steps {
            echo 'rodar os teste'
         }
        }
        stage('UAT') {
         steps {
            echo 'Waiting For User Acceptance'
            input(message: 'Go to Production?', ok: 'Yes')
         }
        }

        stage('prod') {
            steps {
                echo 'Webapp is Ready :D'
         }
        }
   }
}